// <auto-generated />
using System;
using BookingMovie.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingMovie.Migrations
{
    [DbContext(typeof(VeXemPhimContext))]
    [Migration("20211119080612_long")]
    partial class @long
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingMovie.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChieuPhim", b =>
                {
                    b.Property<int>("IdChiTietChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPhim")
                        .HasColumnType("int");

                    b.Property<int>("IdPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime");

                    b.HasKey("IdChiTietChieu")
                        .HasName("PK_ChiTietChieuPhim_1");

                    b.HasIndex("IdPhim");

                    b.HasIndex("IdPhong");

                    b.ToTable("ChiTietChieuPhim");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChoNgoi", b =>
                {
                    b.Property<int>("IdChoNgoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGhe")
                        .HasColumnType("int");

                    b.Property<int>("IdPhong")
                        .HasColumnType("int");

                    b.HasKey("IdChoNgoi");

                    b.HasIndex("IdGhe");

                    b.HasIndex("IdPhong");

                    b.ToTable("ChiTietChoNgoi");
                });

            modelBuilder.Entity("BookingMovie.Models.Ghe", b =>
                {
                    b.Property<int>("IdGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGhe");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("BookingMovie.Models.Phim", b =>
                {
                    b.Property<int>("IdPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTheLoai")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiLuong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPhim");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("Phim");
                });

            modelBuilder.Entity("BookingMovie.Models.PhongChieu", b =>
                {
                    b.Property<int>("IdPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPhong");

                    b.ToTable("PhongChieu");
                });

            modelBuilder.Entity("BookingMovie.Models.TheLoai", b =>
                {
                    b.Property<int>("IdTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTheLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("BookingMovie.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .HasColumnName("SDT")
                        .IsFixedLength(true);

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser")
                        .HasName("PK_KhachHang");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BookingMovie.Models.Ve", b =>
                {
                    b.Property<int>("IdVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdChiTietChieu")
                        .HasColumnType("int");

                    b.Property<int>("IdChoNgoi")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdVe")
                        .HasName("PK_VE");

                    b.HasIndex("IdChiTietChieu");

                    b.HasIndex("IdChoNgoi");

                    b.HasIndex("IdUser");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChieuPhim", b =>
                {
                    b.HasOne("BookingMovie.Models.Phim", "IdPhimNavigation")
                        .WithMany("ChiTietChieuPhims")
                        .HasForeignKey("IdPhim")
                        .HasConstraintName("FK_ChiTietChieuPhim_Phim")
                        .IsRequired();

                    b.HasOne("BookingMovie.Models.PhongChieu", "IdPhongNavigation")
                        .WithMany("ChiTietChieuPhims")
                        .HasForeignKey("IdPhong")
                        .HasConstraintName("FK_ChiTietChieuPhim_PhongChieu")
                        .IsRequired();

                    b.Navigation("IdPhimNavigation");

                    b.Navigation("IdPhongNavigation");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChoNgoi", b =>
                {
                    b.HasOne("BookingMovie.Models.Ghe", "IdGheNavigation")
                        .WithMany("ChiTietChoNgois")
                        .HasForeignKey("IdGhe")
                        .HasConstraintName("FK_ChiTietChoNgoi_Ghe")
                        .IsRequired();

                    b.HasOne("BookingMovie.Models.PhongChieu", "IdPhongNavigation")
                        .WithMany("ChiTietChoNgois")
                        .HasForeignKey("IdPhong")
                        .HasConstraintName("FK_ChiTietChoNgoi_PhongChieu")
                        .IsRequired();

                    b.Navigation("IdGheNavigation");

                    b.Navigation("IdPhongNavigation");
                });

            modelBuilder.Entity("BookingMovie.Models.Phim", b =>
                {
                    b.HasOne("BookingMovie.Models.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("IdTheLoai")
                        .HasConstraintName("FK_Phim_TheLoai")
                        .IsRequired();

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("BookingMovie.Models.Ve", b =>
                {
                    b.HasOne("BookingMovie.Models.ChiTietChieuPhim", "IdChiTietChieuNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("IdChiTietChieu")
                        .HasConstraintName("FK_Ve_ChiTietChieuPhim")
                        .IsRequired();

                    b.HasOne("BookingMovie.Models.ChiTietChoNgoi", "IdChoNgoiNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("IdChoNgoi")
                        .HasConstraintName("FK_Ve_ChiTietChoNgoi1")
                        .IsRequired();

                    b.HasOne("BookingMovie.Models.User", "IdUserNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_Ve_User")
                        .IsRequired();

                    b.Navigation("IdChiTietChieuNavigation");

                    b.Navigation("IdChoNgoiNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChieuPhim", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("BookingMovie.Models.ChiTietChoNgoi", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("BookingMovie.Models.Ghe", b =>
                {
                    b.Navigation("ChiTietChoNgois");
                });

            modelBuilder.Entity("BookingMovie.Models.Phim", b =>
                {
                    b.Navigation("ChiTietChieuPhims");
                });

            modelBuilder.Entity("BookingMovie.Models.PhongChieu", b =>
                {
                    b.Navigation("ChiTietChieuPhims");

                    b.Navigation("ChiTietChoNgois");
                });

            modelBuilder.Entity("BookingMovie.Models.TheLoai", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("BookingMovie.Models.User", b =>
                {
                    b.Navigation("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
